# Page settings

baseurl = "https://damien.codes/"
languageCode = "en-us"
title = "Damien Stanton"
theme = "hugo-orbit-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = false

[params]

# Meta
    description = "Damien Stanton CV"
    author = "Damien Stanton"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-3.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Damien Stanton"
        tagline = "Building next-gen AI"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: damien@blinkanalytics.com"
        title = "email"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel: +2028130150"
        title = "call"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/damienstanton"
        title = "damienstanton"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/damienstanton"
        title = "damienstanton"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/damienstanton"
        title = "@damienstanton"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MITx Certificate: Big Data"
        college = "Massachusetts Institute of Technology"
        dates = "2015"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "Stony Brook University"
        dates = "2004 - 2008"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

        [[params.languages.list]]
        language = "Portuguese"
        level = "Casual"

        [[params.languages.list]]
        language = "Spanish"
        level = "Casual"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Guitar"

        [[params.interests.list]]
        interest = "Art"

        [[params.interests.list]]
        interest = "Quantum Physics"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**I am working towards aritficially intelligent software infrastructure.** To this end, I have spent nearly the entirety of my ~10 years in the field working to help automate systems and make it easier to understand and visualize data. Having used many languages, many tools and many systems over the years, I have come to sip some Google kool-aid and fully endorse their ecosystem and design choices. I firmly believe with the Go language and tools like TensorFlow, App Engine, DataFlow and other things we can build powerfully intelligent systems in a sane and --most importantly-- _fun_ way."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Recent Experience"

        [[params.jobs.list]]
        position = "Founder and CEO"
        dates = "2014 - Present"
        company = "Blink Analytics, Washington DC"
        details = "**My consulting company.** I started Blink Analytics with the goal of delivering intelligent applications, using a unique blend of infrastructure know-how, data science training and hands-on full-stack development. Past clients include Leidos, the US Government Services Administration, StrongDM, and more."

        [[params.jobs.list]]
        position = "Engineer, Information Systems"
        dates = "2013-2014"
        company = "Cvent, Tysons VA"
        details = "**Automation and microservices specialist.** I built automation systems for a 1500+ user VoIP system, a full-stack realtime call-center dashboard, and several internal tools and microservices for the IS division. This role encompassed a wide array of technologies including Java, C#, Python, Go and C++"

        [[params.jobs.list]]
        position = "Senior Systems Engineer"
        dates = "2011 - 2013"
        company = "MadWolf Technologies, Washington, DC"
        details = "**Team lead and RMM automator.** I led a team of support engineers and helped build internal .NET tools to help manage over 25 clients and 50+ petabytes of managed data efficiently. Pioneered the use of scripted remote management tooling from N-Able using Powershell and C#."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**Example open-source code I have worked on.** Here you can see a variety of personal and OSS projects I have contributed to on GitHub."

        [[params.projects.list]]
        title = "TypeReact"
        url = "https://github.com/damienstanton/stanford-corenlp"
        tagline = "A mimimal TypeScript/React/Go app starter kit."

        [[params.projects.list]]
        title = "Stanford CoreNLP"
        url = "https://github.com/damienstanton/stanford-corenlp"
        tagline = "a Clojure port of the Stanford CoreNLP library, partially complete."

        [[params.projects.list]]
        title = "TensorFlow"
        url = "https://github.com/damienstanton/tensorflow"
        tagline = "contributions to Google TensorFlow to get it working better in Go."

        [[params.projects.list]]
        title = "Voice UI"
        url = "https://github.com/damienstanton/voice-ui"
        tagline = "A demo inspired by Fransesc Campoy to build a voice recognition system over the phone."

        [[params.projects.list]]
        title = "Movies"
        url = "https://github.com/damienstanton/movies"
        tagline = "A completion of the Facebook React Native tutorial for iOS."

        [[params.projects.list]]
        title = "Alchemy"
        url = "https://github.com/damienstanton/alchemy-lite"
        tagline = "A public copy of Pedro Domingos' master algorithm from the original source."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Go"
        level = "95%"

        [[params.skills.list]]
        skill = "Python"
        level = "90%"

        [[params.skills.list]]
        skill = "Java/Scala"
        level = "85%"

        [[params.skills.list]]
        skill = "JS"
        level = "80%"

        [[params.skills.list]]
        skill = "C++"
        level = "60%"

        [[params.skills.list]]
        skill = "TensorFlow"
        level = "85%"

        [[params.skills.list]]
        skill = "Apache Spark"
        level = "78%"

        [[params.skills.list]]
        skill = "DeepLearning4J"
        level = "70%"






    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Blink Analytics"
